import AppKit

/// What is on the clipboard, and the two shapes the app is allowed to use it in.
///
/// This is the only place the app reads the clipboard for anything other than pasting, so the
/// limits live here rather than at the call site. One of them is not negotiable: a clipboard a
/// password manager marked concealed is never read at all. Clipboards hold passwords, keys and
/// other people's private messages — the feature is worth having only if that one never slips.
///
/// The two shapes are deliberately different. `reference` goes to the on-device model, capped, and
/// never comes back out. `substituted` goes into the paste verbatim, because a stack trace or a
/// block of code that has been shortened or reworded is worse than useless — but it goes only into
/// the field the user was already about to paste into, only where the marker is, and nowhere else
/// at all. The model that finds the request is never shown the clipboard to do it.
enum ClipboardContext {
    /// Enough for an email, a stack trace or a page of notes; short enough that the model still
    /// answers inside its timeout. A copied document would blow both. This caps what the *model*
    /// is shown, never what is pasted.
    static let referenceLimit = 2000

    /// How much of the clipboard an *assistant* mode reads, about 1,500 tokens.
    ///
    /// Three times what `referenceLimit` lets the cleanup model see, because here the clipboard is
    /// the thing being worked on rather than a spelling hint: a summary of the first 2,000
    /// characters of a document is a wrong summary that looks right. Still a cap — the prompt has
    /// to fit the assistant's context beside the answer — and still the head, for the reason
    /// `reference` is. The person is told when it cut, because a confident answer to half a
    /// document is the failure that costs the most.
    static let materialLimit = 6000

    /// The token that stands where the clipboard goes, from the moment the request is found until
    /// the paste.
    ///
    /// Deliberately not prose: the cleanup model sees it inside the transcript and has to hand it
    /// back untouched, and anything that reads like words gets tidied into different words.
    /// Brackets and capitals are the shape a small model copies most reliably, and no dictated
    /// sentence contains them by accident.
    static let marker = "[[CLIPBOARD]]"

    /// Types that mean "this was not meant to be kept". `ConcealedType` is what 1Password and the
    /// other managers set on a copied password; the rest are the same convention for clipboard
    /// managers, and anything wearing one of them is exactly what must not end up in a prompt.
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func current() -> String? {
        read(from: .general)
    }

    /// Split out from `current()` so a test can drive a private pasteboard. Nothing in the suite
    /// may touch `NSPasteboard.general` — it belongs to whoever is running the tests.
    static func read(from pasteboard: NSPasteboard) -> String? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.contains(where: concealed.contains) else { return nil }

        guard let raw = pasteboard.string(forType: .string) else { return nil }

        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// The clipboard as the on-device model sees it: capped, because the model has a timeout.
    ///
    /// The head, not the tail: what you copied usually starts with the part you care about, and
    /// the ellipsis tells the model the text stops mid-thought rather than mid-sentence.
    static func reference(_ text: String) -> String {
        guard text.count > referenceLimit else { return text }
        return String(text.prefix(referenceLimit)) + "…"
    }

    /// The clipboard as an assistant mode's material: capped at `materialLimit`, and whether it was.
    static func material(_ text: String) -> (text: String, wasCut: Bool) {
        guard text.count > materialLimit else { return (text, false) }
        return (String(text.prefix(materialLimit)), true)
    }

    /// Writes `marker` over the words that asked for the clipboard.
    ///
    /// `request` is what `OnDeviceRefiner.clipboardRequest` found: the model's one job here is to
    /// say *which words* ask, and this is the app doing the editing. Editing is the half a small
    /// model gets wrong — asked to do both in one reply it wrote no marker for any of eight
    /// phrasings — and a plain replacement of text the model has quoted cannot reword anything.
    ///
    /// Only the first occurrence, because the lookup quotes one request. A sentence that was
    /// nothing but the request leaves its full stop behind, and pasting "‹clipboard›." would put
    /// one on the end of whatever was copied; so when no letter or digit is left beside the
    /// marker, the marker is all there is.
    static func marking(_ request: String, in text: String) -> String {
        guard !request.isEmpty, let range = text.range(of: request, options: .caseInsensitive) else { return text }

        let marked = text.replacingCharacters(in: range, with: marker)
        let beside = marked.replacingOccurrences(of: marker, with: "")
        return beside.contains(where: { $0.isLetter || $0.isNumber }) ? marked : marker
    }

    static func hasMarker(_ text: String) -> Bool {
        text.range(of: marker, options: .caseInsensitive) != nil
    }

    /// The clipboard put where `marking` left the marker.
    ///
    /// Saying so — "here is the error, paste what I copied, what does it mean?" — is how you wrap
    /// what you copied in a sentence instead of leaving it dangling at the end. By the time this
    /// runs the position is a literal and there is nothing left to judge.
    ///
    /// No phrase matching, deliberately. The words are spoken, so they never arrive as any phrase
    /// written down in advance — the recogniser declines them, splits the compound, or says them
    /// in another language — and a rule loose enough to catch that is also loose enough to cut open
    /// a sentence that was only *about* the clipboard. The model reads the sentence, and the answer
    /// it gives is checked against it: see `OnDeviceRefiner.request(from:in:)`.
    ///
    /// No marker means nothing is pasted. There used to be a fallback that put the clipboard after
    /// the text whenever the marker was missing, and it fired on every dictation the model was not
    /// asked, declined, or failed to answer — so a mode with this switched on quietly stapled
    /// whatever you had copied onto sentences that never mentioned it. The marker is the only
    /// thing that knows where the clipboard goes; with no marker there is no answer, and no answer
    /// is better than the wrong place.
    ///
    /// Every occurrence is replaced, because saying it twice means twice. Uncapped and untouched:
    /// the user copied this to paste it, and a version the app trimmed to fit a model's context
    /// window would be a silently corrupted paste.
    ///
    /// What does *not* change is the ordering: this runs after the whole refinement pipeline, so
    /// the model is never shown the text it is about to reproduce. It is not shown to the lookup
    /// either — that call sees the sentence and nothing else.
    static func substituted(_ clipboard: String?, into text: String) -> String {
        // No clipboard, so a marker has nothing to stand for and must not reach the document.
        guard let clipboard, !clipboard.isEmpty else { return removingMarker(from: text) }

        // A plain string replacement, so nothing in the clipboard is read as regex syntax — and a
        // text with no marker in it comes back exactly as it went in.
        return text.replacingOccurrences(of: marker, with: clipboard, options: .caseInsensitive)
    }

    /// Takes out a marker that has nothing to stand for, and closes the gap it leaves.
    ///
    /// Reached when the clipboard turned out to be empty or concealed after the model had already
    /// been asked to place it. The three passes are the punctuation the marker was sitting
    /// between: "the error, [[CLIPBOARD]], what?" has to come back as "the error, what?" rather
    /// than "the error, , what?".
    static func removingMarker(from text: String) -> String {
        guard text.range(of: marker, options: .caseInsensitive) != nil else { return text }

        var result = text.replacingOccurrences(of: marker, with: "", options: .caseInsensitive)
        result = replacing(#"([,;:])[ \t]*([,.!?;:])"#, in: result, with: "$2")
        result = replacing(#"[ \t]{2,}"#, in: result, with: " ")
        result = replacing(#"[ \t]+([,.!?;:])"#, in: result, with: "$1")
        return result.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func replacing(_ pattern: String, in text: String, with template: String) -> String {
        guard let regex = RuleRefiner.cachedRegex(pattern) else { return text }
        return regex.stringByReplacingMatches(
            in: text,
            range: NSRange(text.startIndex..., in: text),
            withTemplate: template
        )
    }
}
